### ISSUE TITLE
I dont think the trackpad is working on monterey... Please help!

### ISSUE THREAD

**Issue by VaibhavKukreti-Kathud** [itsmeshibintmz/Acer-Nitro-5-AN515-54-Monterey#1]
I installed macos yesterday using ur EFI as a base but the trackpad doesn't seem to work.. I have the same (ELAN 0504). Please if you could help me fix it :)

**Comment by VaibhavKukreti-Kathud** [comment]
![Screenshot 2022-02-19 at 6 13 46 PM](https://user-images.githubusercontent.com/67002144/154801369-c4e59e8e-d896-42e6-b240-aa89feaebed7.png)

See.. the OS doesn't even detect the trackpad

**Comment by VaibhavKukreti-Kathud** [comment]
Sorry closed the issue by mistake

**Comment by itsmeshibintmz** [comment]
"When using Propertree, do an OC Snapshot of the EFI and also an OC Clean Snapshot. Let me know if it fixes."
Have you tried this?

**Comment by VaibhavKukreti-Kathud** [comment]
Okay so now my trackpad is being detected...
but it doesn't work.. nothing works not even clicking, scrolling... it can't even move the cursor
![Screenshot 2022-02-20 at 12 06 17 PM](https://user-images.githubusercontent.com/67002144/154831616-9b96f673-4c67-4418-b48d-f2d3f323c291.png)

**Comment by VaibhavKukreti-Kathud** [comment]
and on top of that the keyboard also doesn't work i just noticed XD

**Comment by VaibhavKukreti-Kathud** [comment]
The keyboard only works till the login screen to enter my password, once I login, it straight up doesn't work

**Comment by itsmeshibintmz** [comment]
It must be the Voodoo controller kext. Have you tried OC snapshot the EFI and disabling unwanted kexts?

**Comment by VaibhavKukreti-Kathud** [comment]
Yes! I tried OC snapshot too.... @itsmeshibintmz 
what unwanted kexts are you referring to?

**Comment by itsmeshibintmz** [comment]
Voodoo PS2 Controller, when u try OC Snapshot with my EFI, it shows to disable this, after disables do an OC clean snapshot. then the trackpad and keyboard will work fine.

**Comment by ricardomartiinas** [comment]
> Controlador Voodoo PS2, quando você tenta o OC Snapshot com meu EFI, ele mostra para desativar isso, depois de desativar, faça um instantâneo OC clean. então o trackpad e o teclado funcionarão bem. 

 É a primeira vez que uso o propertree e estou com o mesmo problema, o teclado e trackpad não estão funcionando. Me ajude por favor. Obrigado

**Comment by itsmeshibintmz** [comment]
> > Controlador Voodoo PS2, quando você tenta o OC Snapshot com meu EFI, ele mostra para desativar isso, depois de desativar, faça um instantâneo OC clean. então o trackpad e o teclado funcionarão bem.
> 
> É a primeira vez que uso o propertree e estou com o mesmo problema, o teclado e trackpad não estão funcionando. Me ajude por favor. Obrigado

Voodoo PS2 Controller, when u try OC Snapshot with my EFI, it shows to disable this, after disables do an OC clean snapshot. then the trackpad and keyboard will work fine.

**Comment by itsmeshibintmz** [comment]
> > Controlador Voodoo PS2, quando você tenta o OC Snapshot com meu EFI, ele mostra para desativar isso, depois de desativar, faça um instantâneo OC clean. então o trackpad e o teclado funcionarão bem.
> 
> É a primeira vez que uso o propertree e estou com o mesmo problema, o teclado e trackpad não estão funcionando. Me ajude por favor. Obrigado

faça um instantâneo de OC e um instantâneo limpo de OC antes de salvar o EFI com o ProperTree

**Comment by VaibhavKukreti-Kathud** [comment]
> > > Controlador Voodoo PS2, quando você tenta o OC Snapshot com meu EFI, ele mostra para desativar isso, depois de desativar, faça um instantâneo OC clean. então o trackpad e o teclado funcionarão bem.
> > 
> > É a primeira vez que uso o propertree e estou com o mesmo problema, o teclado e trackpad não estão funcionando. Me ajude por favor. Obrigado
> 
> Voodoo PS2 Controller, when u try OC Snapshot with my EFI, it shows to disable this, after disables do an OC clean snapshot. then the trackpad and keyboard will work fine.

Ok I'll try it

**Comment by ricardomartiinas** [comment]
> > > Controlador Voodoo PS2, quando você tenta o OC Snapshot com meu EFI, ele mostra para desativar isso, depois de desativar, faça um instantâneo OC clean. então o trackpad e o teclado funcionarão bem.
> > 
> > 
> > É a primeira vez que uso o propertree e estou com o mesmo problema, o teclado e trackpad não estão funcionando. Me ajude por favor. Obrigado
> 
> faça um instantâneo de OC e um instantâneo limpo de OC antes de salvar o EFI com o ProperTree

Eu fiz do jeito que você falou. O trackpad agora aparece nas preferências de sistema, porém nem o trackpad, nem o teclado funcionam. O jeito vai ser voltar para o Big Sur onde tudo funcionava. Tem mais alguma dica por favor? Obrigado

**Comment by VaibhavKukreti-Kathud** [comment]
@itsmeshibintmz Thanks bro it works for me :)

**Comment by VaibhavKukreti-Kathud** [comment]
@ricardomartiinas My issue has now been fixed that's why i closed the issue.. You of course can open another issue if you have any more problems

**Comment by itsmeshibintmz** [comment]
> Eu fiz do jeito que você falou. O trackpad agora aparece nas preferências de sistema, porém nem o trackpad, nem o teclado funcionam. O jeito vai ser voltar para o Big Sur onde tudo funcionava. Tem mais alguma dica por favor? Obrigado

no, it should be fixed by disabling unwanted kexts with proper tree. I don't know any other solution.

**Comment by ricardomartiinas** [comment]
> My issue has now been fixed that's why i closed the issue.. You of course can open another issue if you have any more problems

Qual etapa resolveu seu problema? Obrigado

**Comment by VaibhavKukreti-Kathud** [comment]
https://github.com/itsmeshibintmz/Acer-Nitro-5-AN515-54-Monterey/issues/1#issuecomment-1050467392

@ricardomartiinas this one
