### ISSUE TITLE
I have ElAN Trackpad and its not working 

### ISSUE THREAD

**Issue by anuppatell** [itsmeshibintmz/Acer-Nitro-5-AN515-54-Monterey#10]
First of all Thankyou for the EFI 

Everything is working fine except my trackpad (Elan Trackpad)

**Comment by VaibhavKukreti-Kathud** [comment]
I think an OC snapshot of the EFI with propertees would do tlit for you... Did you try taking an OC Clean snapshot?

**Comment by itsmeshibintmz** [comment]
> Did you try taking an OC Clean snapshot? In the process it asks to disable a kext you need to approve that...

@anuppatell suggest you give this a shot. I also think this might be the issue. If it helps, update here and in case need help also. Happy to help!

**Comment by itsmeshibintmz** [comment]
Is your issue resolved? @anuppatell

**Comment by itsmeshibintmz** [comment]
Closing this issue as no replies from the issue owner. Hope it is fixed, if not feel free to open one again. Thank you for using the EFI.
