### ISSUE TITLE
On my laptop I think the ethernet is not working can you please help me fix it?

### ISSUE THREAD

**Issue by VaibhavKukreti-Kathud** [itsmeshibintmz/Acer-Nitro-5-AN515-54-Monterey#2]
Connected my laptop to ethernet nothing happened........

**Comment by VaibhavKukreti-Kathud** [comment]
![Screen Shot 2022-03-04 at 4 35 21 PM](https://user-images.githubusercontent.com/67002144/156752305-d3f7c49d-3dfa-4ed1-a027-cebb93930b8c.png)
@itsmeshibintmz

**Comment by itsmeshibintmz** [comment]
have you updated the EFI or kexts?

**Comment by VaibhavKukreti-Kathud** [comment]
> have you updated the EFI or kexts?

Nope, Does it work for you though?

**Comment by itsmeshibintmz** [comment]
> > have you updated the EFI or kexts?
> 
> Nope, Does it work for you though?

yes, everything worked for me except for some I mentioned like Nvidia GPU, HDMI.

**Comment by itsmeshibintmz** [comment]
have you made any changes to the EFI I provided? Is your system specs are same as mine?

**Comment by VaibhavKukreti-Kathud** [comment]
I didn't make any changes to it...

**Comment by itsmeshibintmz** [comment]
Sorry, I don't know. You can try updating kexts or ask in the Hackintosh subreddit.

**Comment by VaibhavKukreti-Kathud** [comment]
![Screenshot 2022-03-04 172903](https://user-images.githubusercontent.com/67002144/156759961-c62758b3-a96b-42a7-89ef-cc860f358a84.png)
I have this showing up in the device manager on windows......

**Comment by VaibhavKukreti-Kathud** [comment]
is this the same ethernet device as you have configured your EFI for?

**Comment by itsmeshibintmz** [comment]
No, I configured for RealTek RTL8168/8111 PCI-E Gigabit Ethernet.
![image](https://user-images.githubusercontent.com/52344717/156760304-f4267f08-3f0e-4ff6-bc45-ced4d70dddfe.png)

**Comment by VaibhavKukreti-Kathud** [comment]
![Screen Shot 2022-03-04 at 4 35 21 PM](https://user-images.githubusercontent.com/67002144/156876386-8da93b0e-52e0-405e-b8fb-088d04b84cc8.png)
Oh well it is being detected but doesn’t connect to the network when i plugin the ethernet

**Comment by itsmeshibintmz** [comment]
Sorry, I don't know. Ask help in the Hackintosh subreddit. Maybe they can help.
