### ISSUE TITLE
Bluetooth Not turning On.

### ISSUE THREAD

**Issue by crazyalok** [itsmeshibintmz/Acer-Nitro-5-AN515-54-Monterey#3]
Hey, I have the same laptop. So i have used your efi. Everything works perfectly just the bluetooth is not turning on in my case. Can you cross check? I have use one other EFI also bluetooth works in that one. But battery backup is not good and touch also does not work in that one.

**Comment by itsmeshibintmz** [comment]
Which one is your Bluetooth?

**Comment by crazyalok** [comment]
I guess it comes with AX-200 card.

**Comment by itsmeshibintmz** [comment]
You can try updating your Bluetooth kext with OC. If not working after that, idk much about this. You can ask r/hackintosh.

**Comment by itsmeshibintmz** [comment]
new efi uploaded, check it out.
