### ISSUE TITLE
Something happens to the speakers though...

### ISSUE THREAD

**Issue by VaibhavKukreti-Kathud** [itsmeshibintmz/Acer-Nitro-5-AN515-54-Monterey#7]
This happens very often..I m just normally using the laptop when suddenly the speaker bugs out and all i hear is hissing and static...I mean the speakers do work but they are very muffled to understand the sound.. Can you please help me fix that? :)

**Comment by itsmeshibintmz** [comment]
> I mean the speakers do work but they are very muffled to understand the sound.. Can you please help me fix that? :)

Open ComboJack installer and give it a try!. Maybe it'll help you fix the issue. Let me know, while I ask some friends using my EFI.

**Comment by itsmeshibintmz** [comment]
> > I mean the speakers do work but they are very muffled to understand the sound.. Can you please help me fix that? :)
> 
> Open ComboJack installer and give it a try!. Maybe it'll help you fix the issue. Let me know, while I ask some friends using my EFI.

https://github.com/itsmeshibintmz/Acer-Nitro-5-AN515-54-Hackintosh/tree/main/ComboJack

**Comment by VaibhavKukreti-Kathud** [comment]
I’ll try that... and just for clarity i am talking of in built speakers...

**Comment by itsmeshibintmz** [comment]
> I’ll try that... and just for clarity i am talking of in built speakers...

Oh, I thought of headphones as most issues occur with Headphones, wait a few days, I'll try to find a fix. Is it okay?

**Comment by itsmeshibintmz** [comment]
In the meantime, try updating kexts n drivers. May it'll do the trick. Most of the time speaker issues are caused by faulty speakers or drivers.

**Comment by VaibhavKukreti-Kathud** [comment]
I actually have almost no idea how this all hackintosh business works lol.. I am entirely dependent on GitHub repos for this regard... So far I only found your EFI working perfectly with the trackpad..😅

**Comment by VaibhavKukreti-Kathud** [comment]
Hence I can't update the opencore version or kexts without breaking the system.. Also Can you tell if it's safe to update to Monterey 12.4?

**Comment by itsmeshibintmz** [comment]
you can update kexts, it won't break the system and update to 12.4.
![Screen Shot 2022-05-29 at 6 33 01 AM](https://user-images.githubusercontent.com/52344717/170848019-49f756e0-0505-40bd-bebb-3307bd102133.png)

I've updated and everything working fine.

**Comment by itsmeshibintmz** [comment]
I'm not experiencing any speaker issues so far, have also asked some using my EFI, and none of them experiencing such issues. I think your speaker is having some issues. Is it working properly on Windows or Linux? If not, please consider visiting a service center.

**Comment by itsmeshibintmz** [comment]
Is it fixed? have you checked with Windows or Linux? (live boot Linux via USB in case you haven't tested)

**Comment by VaibhavKukreti-Kathud** [comment]
I’ve dual booted windows and macos and yes, The speaker works perfectly in windows 11.. I tried updating the kexts.. also that AppleALC one. I’ve not had that issue since then. Hope it stays this way XD

**Comment by itsmeshibintmz** [comment]
That's weird. Try Resetting NVRAM, if not helping, do a clean install with SMBIOS MacBook Pro 16,1 as same in the EFI. It'll work. Never had any issue with the model.
